/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Gerenciadores.GerenciadorCliente;
import Cliente.TelaCliente;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author SloooCk
 */
public class TelaGame extends javax.swing.JFrame {

    private String nomeMeuPresidente;
    int meusPontosTotal;
    int pontosInimigoTotal;
    GerenciadorCliente gerenciadorCliente;

    public TelaGame(String nomeMeuPresidente) {
        initComponents();
        setSize(858, 450);
        this.nomeMeuPresidente = nomeMeuPresidente;
        gerenciadorCliente = new GerenciadorCliente();
        jLabel3.setVisible(false);
        jlMeusPontos.setText("0");
        jlPontosOponente.setText("0");
        jLabel2.setVisible(false);
        jBJogarNovamente.setVisible(false);
        meusPontosTotal = 0;
        jlFotoFinal.setVisible(false);
        pontosInimigoTotal = 0;
        jbSair.setVisible(false);
        jLabel3.setVisible(true);
        jbPedra.setVisible(false);
        jbPapel.setVisible(false);
        jbTesoura.setVisible(false);
        jlMeusPontos.setVisible(false);
        jlPontosOponente.setVisible(false);
        
    }

    public TelaGame() {
        initComponents();
        setSize(858, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jbSair = new javax.swing.JButton();
        jlFotoFinal = new javax.swing.JLabel();
        jbPapel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBJogarNovamente = new javax.swing.JButton();
        jbTesoura = new javax.swing.JButton();
        jbPedra = new javax.swing.JButton();
        jlPontosOponente = new javax.swing.JLabel();
        jlFoto2 = new javax.swing.JLabel();
        jlMeusPontos = new javax.swing.JLabel();
        jlFoto1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 60)); // NOI18N
        jLabel3.setText("Aguarde seu oponente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 760, 210);

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        getContentPane().add(jbSair);
        jbSair.setBounds(290, 360, 80, 23);
        getContentPane().add(jlFotoFinal);
        jlFotoFinal.setBounds(300, 30, 240, 230);

        jbPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Papel.jpg"))); // NOI18N
        jbPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPapelActionPerformed(evt);
            }
        });
        getContentPane().add(jbPapel);
        jbPapel.setBounds(350, 180, 140, 140);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 50)); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 250, 500, 90);

        jBJogarNovamente.setText("Jogar Novamente");
        jBJogarNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJogarNovamenteActionPerformed(evt);
            }
        });
        getContentPane().add(jBJogarNovamente);
        jBJogarNovamente.setBounds(420, 360, 190, 23);

        jbTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tesoura.jpg"))); // NOI18N
        jbTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTesouraActionPerformed(evt);
            }
        });
        getContentPane().add(jbTesoura);
        jbTesoura.setBounds(550, 180, 140, 140);

        jbPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pedra.jpg"))); // NOI18N
        jbPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedraActionPerformed(evt);
            }
        });
        getContentPane().add(jbPedra);
        jbPedra.setBounds(143, 183, 140, 140);

        jlPontosOponente.setFont(new java.awt.Font("Arial Black", 0, 80)); // NOI18N
        jlPontosOponente.setText("0");
        getContentPane().add(jlPontosOponente);
        jlPontosOponente.setBounds(300, 20, 60, 70);
        getContentPane().add(jlFoto2);
        jlFoto2.setBounds(220, 20, 60, 70);

        jlMeusPontos.setFont(new java.awt.Font("Arial Black", 0, 80)); // NOI18N
        jlMeusPontos.setText("0");
        getContentPane().add(jlMeusPontos);
        jlMeusPontos.setBounds(120, 20, 60, 70);
        getContentPane().add(jlFoto1);
        jlFoto1.setBounds(50, 20, 60, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 842, 414);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void imagemIcon(String diretorio) {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/Imagens/" + diretorio));
        jlFoto1.setIcon(imagem);
    }

    public void imagemIconOponente(String diretorio) {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/Imagens/" + diretorio));
        jlFoto2.setIcon(imagem);
    }

    public void imagemIconFinal(String diretorio) {
        ImageIcon imagem = new ImageIcon(getClass().getResource("/Imagens/" + diretorio));
        jlFotoFinal.setIcon(imagem);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //=============conectanco cliente no servidor=========
            gerenciadorCliente.conectaNoServidor();
            String resposta = gerenciadorCliente.ouveServidor();
            System.out.println(resposta);
            if (resposta.equals("AGUARDE CONEXÃO DE OUTRO CLIENTE")) {
                /*jLabel3.setVisible(true);
                jbPedra.setVisible(false);
                jbPapel.setVisible(false);
                jbTesoura.setVisible(false);
                 */
                System.out.println("a");
                System.out.println(gerenciadorCliente.ouveServidor());

            }
            jbPedra.setVisible(true);
            jbPapel.setVisible(true);
            jbTesoura.setVisible(true);
            jLabel3.setVisible(false);
            jlMeusPontos.setVisible(true);
            jlPontosOponente.setVisible(true);
            //=============conectanco cliente no servidor=========

            if (nomeMeuPresidente.equals("DILMA")) {
                gerenciadorCliente.comunica("DILMA");
                imagemIcon("DilmaPequena.jpg");
            } else if (nomeMeuPresidente.equals("FRANK")) {
                gerenciadorCliente.comunica("FRANK");
                imagemIcon("FrankPequeno.jpg");
            } else if (nomeMeuPresidente.equals("TEMER")) {
                gerenciadorCliente.comunica("TEMER");
                imagemIcon("TemerPequeno.jpg");
            }

            String presOponente = gerenciadorCliente.ouveServidor();

            if (presOponente.equals("DILMA")) {
                imagemIconOponente("DilmaPequena.jpg");
            } else if (presOponente.equals("FRANK")) {
                imagemIconOponente("FrankPequeno.jpg");
            } else if (presOponente.equals("TEMER")) {
                imagemIconOponente("TemerPequeno.jpg");
            }

            /*    
            rbPapel.setEnabled(true);
            rbPedra.setEnabled(true);
            rbTesoura.setEnabled(true);
            jButton1.setEnabled(true);
             */
        } catch (IOException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formWindowOpened

    private void jbPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPapelActionPerformed
        mandaMensagem("PAPEL");
    }//GEN-LAST:event_jbPapelActionPerformed

    public void desativaBotoes(){
         jbPedra.setEnabled(false);
        jbPapel.setEnabled(false);
        jbTesoura.setEnabled(false);    
    }
    private void jbTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTesouraActionPerformed
        mandaMensagem("TESOURA");
    }//GEN-LAST:event_jbTesouraActionPerformed

    public void mandaMensagem(String mensagem) {

        String escolha = "";
        int quantidadePontos = 0;
        String meusPontos, pontosInimigos, resposta;

        escolha = mensagem;
        try {
            gerenciadorCliente.comunica(escolha);
            
            resposta = gerenciadorCliente.ouveServidor();
            
            System.out.println("Meu Ponto " + resposta);
            if (resposta.equals("VENCEU")) {
                meusPontosTotal = meusPontosTotal + 1;
            } else if (resposta.equals("PERDEU")) {
                pontosInimigoTotal = pontosInimigoTotal + 1;
            } else if (resposta.equals("EMPATE")) {

            }
            //System.out.println("Ponto inimigo "+pontosInimigos);
            jlMeusPontos.setText(meusPontosTotal + "");
            jlPontosOponente.setText(pontosInimigoTotal + "");
            if (meusPontosTotal == 3 || pontosInimigoTotal == 3) {
                jbPedra.setVisible(false);
                jbPapel.setVisible(false);
                jbTesoura.setVisible(false);
                jlFoto1.setVisible(false);
                jlMeusPontos.setVisible(false);
                jlFoto2.setVisible(false);
                jlPontosOponente.setVisible(false);
                jbSair.setVisible(true);
                jBJogarNovamente.setVisible(true);

                if (meusPontosTotal == 3) {
                    jLabel2.setVisible(true);
                    jLabel2.setText("VOCÊ VENCEU");

                    if (nomeMeuPresidente.equals("DILMA")) {
                        imagemIconFinal("DilmaSorrindo.jpg");
                    } else if (nomeMeuPresidente.equals("FRANK")) {
                        imagemIconFinal("FrankFeliz.jpg");
                    } else if (nomeMeuPresidente.equals("TEMER")) {
                        imagemIconFinal("TemerFeliz.jpg");
                    }
                    jlFotoFinal.setVisible(true);

                } else if (pontosInimigoTotal == 3) {
                    jLabel2.setVisible(true);
                    jLabel2.setText("VOCÊ PERDEU");
                    if (nomeMeuPresidente.equals("DILMA")) {
                        imagemIconFinal("DilmaTriste.jpg");
                    } else if (nomeMeuPresidente.equals("FRANK")) {
                        imagemIconFinal("FrankTriste.jpg");
                    } else if (nomeMeuPresidente.equals("TEMER")) {
                        imagemIconFinal("TemerTriste.jpg");
                    }
                    jlFotoFinal.setVisible(true);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaGame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jbPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedraActionPerformed
        mandaMensagem("PEDRA");
    }//GEN-LAST:event_jbPedraActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        try {
            gerenciadorCliente.comunica("Não");
        } catch (IOException ex) {
            Logger.getLogger(TelaGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jBJogarNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJogarNovamenteActionPerformed
        try {
            gerenciadorCliente.comunica("Sim");
        } catch (IOException ex) {
            Logger.getLogger(TelaGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaPresidente form = new TelaPresidente();
        form.setLocationRelativeTo(form);
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBJogarNovamenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBJogarNovamente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbPapel;
    private javax.swing.JButton jbPedra;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbTesoura;
    private javax.swing.JLabel jlFoto1;
    private javax.swing.JLabel jlFoto2;
    private javax.swing.JLabel jlFotoFinal;
    private javax.swing.JLabel jlMeusPontos;
    private javax.swing.JLabel jlPontosOponente;
    // End of variables declaration//GEN-END:variables
}
