/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import Gerenciadores.GerenciadorCliente;
import java.io.IOException;
import java.io.PrintStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SloooCk
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    Socket cliente;
    EstadoTela estadoTela;
    GerenciadorCliente gerenciadorCliente;
    int meusPontosTotal;
    int pontosInimigoTotal;
    public TelaCliente() {
        initComponents();
        estadoTela = EstadoTela.NÃO_PERMITIDO;
        gerenciadorCliente = new GerenciadorCliente();
        jlMeusPontos.setText("0");
        jlPontosInimigo.setText("0");
        meusPontosTotal =0;
        pontosInimigoTotal =0;
        rbPapel.setEnabled(false);
        rbPedra.setEnabled(false);
        rbTesoura.setEnabled(false);
        jButton1.setEnabled(false);
        jLabel2.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbPapel = new javax.swing.JRadioButton();
        rbPedra = new javax.swing.JRadioButton();
        rbTesoura = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlMeusPontos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlPontosInimigo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonGroup1.add(rbPapel);
        rbPapel.setText("Papel");

        buttonGroup1.add(rbPedra);
        rbPedra.setText("Pedra");

        buttonGroup1.add(rbTesoura);
        rbTesoura.setText("Tesoura");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pontos:");

        jlMeusPontos.setText("jLabel2");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Pontos:");

        jlPontosInimigo.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbPedra)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbPapel)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbTesoura)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlMeusPontos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPontosInimigo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel2)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jlPontosInimigo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jlMeusPontos)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPedra)
                    .addComponent(rbPapel)
                    .addComponent(rbTesoura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String escolha="";
        int quantidadePontos =0;
        String meusPontos,pontosInimigos,resposta;
        if(rbPedra.isSelected())
        {
            escolha = "PEDRA";
        }else if(rbPapel.isSelected())
        {
            escolha = "PAPEL";
        }else if(rbTesoura.isSelected())
        {
            escolha = "TESOURA";
        }
        try {
            gerenciadorCliente.comunica(escolha);
             resposta = gerenciadorCliente.ouveServidor();
            //pontosInimigos = gerenciadorCliente.ouveServidor();
            System.out.println("Meu Ponto "+resposta);
            if(resposta.equals("VENCEU"))
            {
                meusPontosTotal =meusPontosTotal+ 1;
            }else if(resposta.equals("PERDEU")){
                pontosInimigoTotal = pontosInimigoTotal+1;
            }else if(resposta.equals("EMPATE")){
                
            }
            //System.out.println("Ponto inimigo "+pontosInimigos);
            jlMeusPontos.setText(meusPontosTotal+"");
            jlPontosInimigo.setText(pontosInimigoTotal+"");
            
            if(meusPontosTotal==3 || pontosInimigoTotal==3)
            {
                if(meusPontosTotal==3)
                {
                    jLabel2.setVisible(true);
                    jLabel2.setText("VOCÊ VENCEU");
                }else if(pontosInimigoTotal==3){
                    jLabel2.setVisible(true);
                    jLabel2.setText("VOCÊ PERDEU");
                }
            }
            /*if(meusPontos.equals("0")||meusPontos.equals("1")){
                jlPontos.setText(Integer.parseInt(jlPontos.getText())+Integer.parseInt(meusPontos)+"");
            }
            */
        } catch (IOException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          
        try {
            gerenciadorCliente.conectaNoServidor();
            String resposta = gerenciadorCliente.ouveServidor();
            System.out.println(resposta);
            rbPapel.setEnabled(true);
            rbPedra.setEnabled(true);
            rbTesoura.setEnabled(true);
            jButton1.setEnabled(true);
            
        } catch (IOException ex) {
            Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlMeusPontos;
    private javax.swing.JLabel jlPontosInimigo;
    private javax.swing.JRadioButton rbPapel;
    private javax.swing.JRadioButton rbPedra;
    private javax.swing.JRadioButton rbTesoura;
    // End of variables declaration//GEN-END:variables
}
